/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { clientsClaim } from 'workbox-core';

declare const self: ServiceWorkerGlobalScope;

const SW_VERSION = '1.0.1';
console.log(`[SW ${SW_VERSION}] Service Worker initializing...`);

// Force the new service worker to take control immediately
self.skipWaiting();
clientsClaim();

// Clean up old caches from previous versions
cleanupOutdatedCaches();

// Log install event
self.addEventListener('install', (event) => {
  console.log(`[SW ${SW_VERSION}] INSTALL event - precaching assets`);
});

// Log activate event
self.addEventListener('activate', (event) => {
  console.log(`[SW ${SW_VERSION}] ACTIVATE event - taking control`);
});

// Precache all assets generated by Vite
console.log(`[SW ${SW_VERSION}] Calling precacheAndRoute...`);
const manifest = self.__WB_MANIFEST;
console.log(`[SW ${SW_VERSION}] Precache manifest has ${manifest.length} entries`);
precacheAndRoute(manifest);

// App Shell - Cache First
registerRoute(
  ({ url }) => url.origin === self.location.origin,
  new CacheFirst({
    cacheName: 'app-shell',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  })
);

// External CDN Dependencies (React, Framer Motion, Lucide) - Cache First
registerRoute(
  /^https:\/\/aistudiocdn\.com\/.*/i,
  new CacheFirst({
    cacheName: 'external-dependencies',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Unsplash Images - Cache First
registerRoute(
  /^https:\/\/images\.unsplash\.com\/.*/i,
  new CacheFirst({
    cacheName: 'tour-images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Google Fonts Stylesheets - Cache First
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-stylesheets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
    ],
  })
);

// Google Font Files - Cache First
registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
    ],
  })
);

// Supabase Audio Files - Cache First
registerRoute(
  ({ url }) => {
    return (
      url.origin === 'https://ewrhpiibxstiipkqafwf.supabase.co' &&
      url.pathname.includes('/storage/v1/object/public/') &&
      (url.pathname.endsWith('.mp3') ||
        url.pathname.endsWith('.wav') ||
        url.pathname.endsWith('.m4a'))
    );
  },
  new CacheFirst({
    cacheName: 'tour-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Supabase Images - Cache First
registerRoute(
  ({ url }) => {
    return (
      url.origin === 'https://ewrhpiibxstiipkqafwf.supabase.co' &&
      url.pathname.includes('/storage/v1/object/public/') &&
      (url.pathname.endsWith('.jpg') ||
        url.pathname.endsWith('.jpeg') ||
        url.pathname.endsWith('.png') ||
        url.pathname.endsWith('.webp'))
    );
  },
  new CacheFirst({
    cacheName: 'tour-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Supabase Videos - Cache First
registerRoute(
  ({ url }) => {
    return (
      url.origin === 'https://ewrhpiibxstiipkqafwf.supabase.co' &&
      url.pathname.includes('/storage/v1/object/public/') &&
      (url.pathname.endsWith('.mp4') || url.pathname.endsWith('.webm'))
    );
  },
  new CacheFirst({
    cacheName: 'tour-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Supabase 3D Models - Cache First
registerRoute(
  ({ url }) => {
    return (
      url.origin === 'https://ewrhpiibxstiipkqafwf.supabase.co' &&
      url.pathname.includes('/storage/v1/object/public/') &&
      (url.pathname.endsWith('.glb') || url.pathname.endsWith('.gltf'))
    );
  },
  new CacheFirst({
    cacheName: 'tour-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Add detailed fetch logging
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  const isNavigationRequest = event.request.mode === 'navigate';

  console.log(`[SW ${SW_VERSION}] FETCH ${event.request.method} ${url.href}`, {
    mode: event.request.mode,
    destination: event.request.destination,
    isNavigation: isNavigationRequest,
    origin: url.origin,
  });
});

// Clean up old caches
self.addEventListener('activate', (event) => {
  console.log(`[SW ${SW_VERSION}] ACTIVATE - cleaning old caches`);
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      console.log(`[SW ${SW_VERSION}] Found caches:`, cacheNames);
      return Promise.all(
        cacheNames
          .filter((cacheName) => {
            // Delete old caches that don't match current cache names
            const shouldDelete = !cacheName.match(
              /^(app-shell|external-dependencies|tour-images|google-fonts-stylesheets|google-fonts-webfonts|tour-assets|workbox-precache)/
            );
            if (shouldDelete) {
              console.log(`[SW ${SW_VERSION}] Deleting old cache: ${cacheName}`);
            }
            return shouldDelete;
          })
          .map((cacheName) => caches.delete(cacheName))
      );
    })
  );
});
