/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// App Shell - Cache First
registerRoute(
  ({ url }) => url.origin === self.location.origin,
  new CacheFirst({
    cacheName: 'app-shell',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  })
);

// External CDN Dependencies (React, Framer Motion, Lucide) - Cache First
registerRoute(
  /^https:\/\/aistudiocdn\.com\/.*/i,
  new CacheFirst({
    cacheName: 'external-dependencies',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Unsplash Images - Cache First
registerRoute(
  /^https:\/\/images\.unsplash\.com\/.*/i,
  new CacheFirst({
    cacheName: 'tour-images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Google Fonts Stylesheets - Cache First
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-stylesheets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
    ],
  })
);

// Google Font Files - Cache First
registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
    ],
  })
);

// Supabase Audio Files - Cache First
registerRoute(
  ({ url }) => {
    return (
      url.origin === 'https://ewrhpiibxstiipkqafwf.supabase.co' &&
      url.pathname.includes('/storage/v1/object/public/') &&
      (url.pathname.endsWith('.mp3') ||
        url.pathname.endsWith('.wav') ||
        url.pathname.endsWith('.m4a'))
    );
  },
  new CacheFirst({
    cacheName: 'tour-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Supabase Images - Cache First
registerRoute(
  ({ url }) => {
    return (
      url.origin === 'https://ewrhpiibxstiipkqafwf.supabase.co' &&
      url.pathname.includes('/storage/v1/object/public/') &&
      (url.pathname.endsWith('.jpg') ||
        url.pathname.endsWith('.jpeg') ||
        url.pathname.endsWith('.png') ||
        url.pathname.endsWith('.webp'))
    );
  },
  new CacheFirst({
    cacheName: 'tour-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Supabase Videos - Cache First
registerRoute(
  ({ url }) => {
    return (
      url.origin === 'https://ewrhpiibxstiipkqafwf.supabase.co' &&
      url.pathname.includes('/storage/v1/object/public/') &&
      (url.pathname.endsWith('.mp4') || url.pathname.endsWith('.webm'))
    );
  },
  new CacheFirst({
    cacheName: 'tour-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Supabase 3D Models - Cache First
registerRoute(
  ({ url }) => {
    return (
      url.origin === 'https://ewrhpiibxstiipkqafwf.supabase.co' &&
      url.pathname.includes('/storage/v1/object/public/') &&
      (url.pathname.endsWith('.glb') || url.pathname.endsWith('.gltf'))
    );
  },
  new CacheFirst({
    cacheName: 'tour-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Clean up old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames
          .filter((cacheName) => {
            // Delete old caches that don't match current cache names
            return !cacheName.match(
              /^(app-shell|external-dependencies|tour-images|google-fonts-stylesheets|google-fonts-webfonts|tour-assets|workbox-precache)/
            );
          })
          .map((cacheName) => caches.delete(cacheName))
      );
    })
  );
});
